name: CI

on:
  push:
    branches: [macposts]
  pull_request:
    branches: [macposts]

jobs:
  standard:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      shell: bash
      run: |
        if [ "$RUNNER_OS" == 'Windows' ]; then
          cmake -DSNAP_BUILD_TESTS=OFF -S . -B .
        else
          cmake -DSNAP_BUILD_TESTS=ON -S . -B .
        fi

    - name: Build
      run: cmake --build . --verbose

    - name: Test
      run: ctest
      if: runner.os != 'Windows'
