name: CI

on:
  push:
    branches: [macposts]
  pull_request:
    branches: [macposts]

jobs:
  standard:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: cmake -DSNAP_BUILD_TESTS=ON -S . -B .

    - name: Build
      run: cmake --build . --verbose

    - name: Test
      run: ctest
